### ISSUE TITLE
[BUG] Marking an article as deprecated does literally nothing

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#12]
### Problem

When marking pages as deprecated, there is no indication that it is actually deprecated.

### Expected

There is some sort of indication that a page is deprecated, like the orange bubble shown on the home page, and potentially a banner on the top of the article.

**Comment by RobertRR11** [comment]
was previously only on the navigation menu and seems like it has been forgotten on the main page

**Comment by 3vorp** [comment]
~~I kinda forgot the navigation bar even existed lol~~
