### ISSUE TITLE
[BUG] Links in table of contents don't scroll the screen far enough.

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#13]
## Problem

When using IDs such as in the table of contents on the docs site to find a specific entry (the texturing guidelines use this a lot), the screen doesn't move to the proper area and instead falls a bit short.

## Expected Outcome

When using these URLs they move the screen down to the proper area.

## Examples / How to reproduce

1. Navigate to the following URL: https://docs.faithfulpack.net/pages/textures/texturing-guidelines#credits
2. Notice how it doesn't actually move the screen to the credits section and stops a bit short.

**Comment by TheRolfFR** [comment]
I think this is due to lazy loading of images, no simple solution either, and I don't think both are compatible

**Comment by 3vorp** [comment]
either way figured I ought to bring it up as it's a pain when quoting stuff and the whole table of content feature is essentially completely broken as a result

**Comment by 3vorp** [comment]
the new commit seems to work perfectly so I'm gonna close this

**Comment by TheRolfFR** [comment]
I surrounded the Waypoint with a div and a width and an aspect ratio to force an empty space corresponding to the image size
