### ISSUE TITLE
[Features] Improve the navigation bar

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#17]
I literally had no idea the navigation bar even existed until a few weeks ago, so it would be nice to make it a bit more user-friendly and visible.

- [x] When opened, let it stay open and you can keep using the docs site like normal. If it would just slide the text over to the right a bit instead of covering everything, it would be a lot more convenient to use and could even be opened by default when looking at a doc.

- [x] Have the categories open by default. Right now, to navigate to a specific page you have to click the specific category before doing so, it would be much more convenient to make it collapsable but open by default, similar to how Discord handles channel categories.

- [x] Make the theme settings consistent with either the main site or make the main site consistent with this — currently the main site has the theme settings in the footer but here and in the webapp it's on the sidebar, either way is fine just make it consistent.

**Comment by RobertRR11** [comment]
> Move the theme settings to the footer. This is how the main site does it and I keep going to the bottom of pages to find the toggle, this would be way more consistent and convenient.

This is actually more of an issue with the main site. Most sites that I know of actually use the theme toggle in the navigation bar instead of in the footer.

**Comment by TheRolfFR** [comment]
More fixes in 72085427e99a8804177f31b07a065a4f754ad66d

**Comment by RobertRR11** [comment]
I noticed that the table of contents don't move with the navigation bar opened, for example https://docs.faithfulpack.net/pages/textures/texturing-guidelines

**Comment by 3vorp** [comment]
> More fixes in [7208542](https://github.com/Faithful-Resource-Pack/Docs/commit/72085427e99a8804177f31b07a065a4f754ad66d)

yes this is perfect thank you

**Comment by 3vorp** [comment]
> I noticed that the table of contents don't move with the navigation bar opened, for example https://docs.faithfulpack.net/pages/textures/texturing-guidelines

til that the table of contents is supposed to move down, I always thought it was like how wikipedia did it just using it below the summary and above the actual descriptions

kinda not a fan of this tbh, it adds a bit of clutter to the screen and doesn't really look nice to me
