### ISSUE TITLE
[Feature] Use the stone background on the docs page rather than a plain background

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#18]
For some reason the only place the background is used on the docs site currently is in the navigation bar under the logo, and the rest uses a plain background.

It might also hinder visibility a bit, which is why I'm not entirely sure whether this should be implemented, but I figured I should bring it up anyways.

**Comment by Juknum** [comment]
I'm okay with the current plain background, it improves readability by a lot, and we don't have to deal with alignment aha

If you have any preview on how it should/would looks like, feel free to add screenshots there, but I prefer to keep the current setup we have :)

**Comment by Pomi108** [comment]
I agree with Juknum here, I think using the stone background would make everything less readable. Even on the main website we use a plain box behind article bodies.

**Comment by 3vorp** [comment]
fair enough just figured I'd bring it up
