### ISSUE TITLE
Site build time is abnormally long

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#19]
## What happened?

When making a new commit to this GitHub repository, the site automatically deploys and builds on our VPS. However, the images have not appeared to recompile in some months despite many of them changing. This results in outdated images even though they've been pushed to the repository.

## To reproduce

1. Change an image on the GitHub repository.
2. Wait until the deployment has finished.
3. Check the docs site, and notice that the image has not updated, even after clearing cache, using a different browser, or even a different device.

## Screenshot(s)

<img width="1325" alt="Screen Shot 2023-03-19 at 9 30 15 AM" src="https://user-images.githubusercontent.com/75297863/226190140-0e915b63-3495-43b4-b92f-a64c82cbcffb.png">

<img width="1181" alt="Screen Shot 2023-03-19 at 9 30 31 AM" src="https://user-images.githubusercontent.com/75297863/226190158-179257ff-a416-49d0-b78a-fe37cbb2926f.png">

*Notice how the image on the docs site hasn't updated despite a commit being made nearly six months ago.*

**Browser name and version**

Multiple browsers (tested on Chrome, Firefox, and Brave).

**Notes**

May be related to [this commit](https://github.com/Faithful-Resource-Pack/Docs/commit/88704edbd97b8976ad80ae694afb53b5433c2763) or [this commit](https://github.com/Faithful-Resource-Pack/Docs/commit/c866aef944b921bfa8dbe061d5cc5287f3b28d48), both of which optimized build times.

**Comment by TheRolfFR** [comment]
I changed the thumbnail generation process so you should have the latest images version.

**Comment by 3vorp** [comment]
the odd thing is that #14 seems to have actually returned with this change? The build time is really slow again, which is really different to every other site, many of which implement images directly within their repos.

**Comment by 3vorp** [comment]
<img width="1240" alt="Screen Shot 2023-03-27 at 10 11 58 AM" src="https://user-images.githubusercontent.com/75297863/228015906-d03bbf96-dc2f-4745-9284-21e6be0665fd.png">
you can see that the times increased from ~50 seconds to ~7 minutes from when that commit was made here

**Comment by TheRolfFR** [comment]
Is this still relevant? @RobertRR11 moved the build process on the VPS with commit 88704ed

**Comment by 3vorp** [comment]
for some reason fixing the image recompile issue made the build times super long again, despite it compiling on the vps it's now taking minutes to deploy rather than ~30 seconds

**Comment by TheRolfFR** [comment]
I think the build time can be reasonably considered as acceptable, we will reopen if very long in the future
