### ISSUE TITLE
[Feature] Improve table of contents to be more consistent with other documentation sites.

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#20]
### Describe the feature you'd like

Currently, the table of contents is on the right side of the screen and cannot be hidden.  I don't know of like any site which uses the right side for a table of contents, either it's on the left like wikipedia or integrated into the sidebar.

I would like to suggest that we move the table of contents inside the navbar under a dropdown menu in the articles. When opening an article, it would automatically open and be visible, but you could collapse it at any time using an arrow button (similar to Discord categories) or even just hide the navigation menu.

Not only will this bring some valuable screen space back, but it's consistent with most other documentation sites (see the Discord.py documentation example attached below).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/75297863/226644645-7e59ab54-3fd4-4d9a-b691-b9d3bab423cf.png)

<img width="239" alt="Screen Shot 2023-03-21 at 7 54 35 AM" src="https://user-images.githubusercontent.com/75297863/226645977-7dacb17d-1cfe-4638-9f20-72d59eaca0fb.png">

### Notes

Also would be nice to try and fix issue https://github.com/Faithful-Resource-Pack/Docs/issues/13 in the process.
EDIT: This has been implemented.

**Comment by TheRolfFR** [comment]
I would not recommend putting the table of content inside the navbar as it is already pretty crowded.
Also I think separating both would make more sense.
In you discord.py documentation example, the layout is different as we have much more pages and a navigation drawer.
Electron documentation is much closer to what we have (https://www.electronjs.org/docs/latest/tutorial/installation) and it doesn't affect the read quality.
![image](https://github.com/Faithful-Resource-Pack/Docs/assets/18086786/667d7843-9972-425e-93fb-8c08d57f4568)

**Comment by 3vorp** [comment]
I'd be fine with that too, actually it's a bit close to what I imagined — discord.py was just an example that came into mind at the time

**Comment by 3vorp** [comment]
I suppose? but I feel like Faithful applies more to the discord.py example since we have much more complicated articles with a lot of nested headings, plus the sidebar is used a lot more effectively here than on the faithful docs site where you pretty much only use it to switch to completely unrelated articles rather than here where it seems like you're going through a tutorial on how to use the program and would keep going down the list on the left

**Comment by TheRolfFR** [comment]
Okay, you're right. Would you like to load all tables of contents in nav or just the currently loaded page? All tables of content may be difficult

**Comment by 3vorp** [comment]
every article having a visible dropdown at once would be nice if that's not too difficult, but I understand your concerns and would be fine with having just the currently loaded page have the table of contents opened

**Comment by 3vorp** [comment]
just found the linux kernel docs have pretty much exactly the same setup that I'm asking for, including category titles etc

https://www.kernel.org/doc/html/v4.10/process/development-process.html

it only shows top-level headings on the sidebar which I quite like — we could just grab all h1 elements and display those titles on the left bar

also, I really like how the table of contents is both present at the start of the article and on the sidebar — if you want each subpoint carefully listed out you can go to the top of the article but you can go to the main talking points anywhere in the article

**Comment by 3vorp** [comment]
completed with #24
