### ISSUE TITLE
[Bug] Entire pages are off-center in specific scenarios.

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Docs#22]
### What happened?

Pretty much exactly what the title says — by opening and collapsing the navigation menu in specific orders you can cause pages to not center properly.

### To reproduce

1. Go to https://docs.faithfulpack.net/.
2. Open the navigation sidebar.
3. Navigate to any article that does not contain a table of contents.
4. Collapse the navigation sidebar.
5. Notice how the whole page is off centered to the left.

This persists even after clicking through any number of articles and even on the home page, until you refresh the site.

### Screenshot(s)

with the bug:
<img width="1680" alt="Screen Shot 2023-03-26 at 11 54 58 AM" src="https://user-images.githubusercontent.com/75297863/227797720-df91c36a-d20a-49ab-9dfd-a0261fbb135c.png">
how it's supposed to look:
<img width="1680" alt="Screen Shot 2023-03-26 at 11 55 13 AM" src="https://user-images.githubusercontent.com/75297863/227797733-4b897564-083f-4bea-8042-fa894bd0bc79.png">

### Browser name and version

Brave Version 1.49.128
Chromium: 111.0.5563.110

### Notes

May be related to the table of contents since it seems to be offset by the right amount to make the table of contents fit if there was one.

Ideally implement #20 if this is part of the issue.

**Comment by TheRolfFR** [comment]
Culprit seems to be;
https://github.com/Faithful-Resource-Pack/Docs/blob/54e3e8c2c92fab55dfa36ec61f898bbf376d2fc8/src/routes/layout.svelte#L39
